### ISSUE TITLE
Can't return list of object [Cursor Objects]

### ISSUE THREAD

**Issue by giboow** [anboralabs/spatia-room#1]
Hi! I have just test your library for one of my project. It works fine, but not for my case...

I wan't to return a list of object, but the use of  @SkipQueryVerification annontation generate an error when I compile my project.

`Error:Not sure how to convert a Cursor to this method's return type`

**Comment by dalgarins** [comment]
Could you share a little more information about the issue? please, could you share the Dao interface?.

**Comment by dalgarins** [comment]
To solve the issue with `Cursors` It's necessary to modify `AndroidX Components Room`, because they use a memory database to validate queries and `@SkipQueryVerification` is not compatible with Cursors. 

The solution for `AndroidX`, should be create a `JDBC Driver` for `spatialite` and use it in room query validations of `AndroidX`. With that implementation we could delete annotation `@SkipQueryVerification` for `spatialite` queries.

**Comment by dalgarins** [comment]
In future versions I will fix it for now is not a priority.
